#!/usr/bin/env bash
# =============================================================================
# NexusLayer SDK & Skills Installer
#
# Usage:
#   bash install.sh <YOUR_NEXUSLAYER_API_KEY>
#
# Gets your API key from: https://identity.nexuslayer.eu → Profile → API Key
# =============================================================================

set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; CYAN='\033[0;36m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC}  $1"; }
info() { echo -e "${CYAN}→${NC}  $1"; }
warn() { echo -e "${YELLOW}⚠${NC}  $1"; }
fail() { echo -e "${RED}✗${NC}  $1"; exit 1; }

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Token ───────────────────────────────────────────────────────────────────

TOKEN="${1:-}"

if [ -z "$TOKEN" ]; then
  echo ""
  echo -e "${CYAN}NexusLayer SDK & Skills Installer${NC}"
  echo "────────────────────────────────────"
  echo ""
  echo "Get your API key from: https://identity.nexuslayer.eu → Profile → API Key"
  echo ""
  read -r -p "Paste your NexusLayer API key: " TOKEN
fi

if [ -z "$TOKEN" ]; then
  fail "No API key provided. Exiting."
fi

if [[ "$TOKEN" != eyJ* ]]; then
  fail "Token does not look like a NexusLayer JWT (should start with 'eyJ'). Check https://identity.nexuslayer.eu"
fi

echo ""
echo -e "${CYAN}NexusLayer SDK & Skills Installer${NC}"
echo "────────────────────────────────────"
echo ""

# ─── Validate token ──────────────────────────────────────────────────────────

info "Validating token against identity.nexuslayer.eu..."
HTTP_CODE=$(curl -sk -o /dev/null -w "%{http_code}" \
  -H "Authorization: Bearer $TOKEN" \
  https://identity.nexuslayer.eu/api/v1/users/me 2>/dev/null || echo "000")

if [ "$HTTP_CODE" = "200" ]; then
  ok "Token is valid"
elif [ "$HTTP_CODE" = "000" ]; then
  warn "Could not reach identity.nexuslayer.eu — proceeding anyway (offline install)"
else
  fail "Token rejected (HTTP $HTTP_CODE). Get a fresh key from https://identity.nexuslayer.eu → Dashboard → API Keys.\n   Still stuck? Email admin@nexuslayer.eu with the HTTP code above."
fi

# ─── Skills ──────────────────────────────────────────────────────────────────

SKILLS_DIR="${HOME}/.claude/skills"
SKILLS=(agentbrain agentvault brainvault markvault docvault modelrouter switchboard
        codereviewai taskrelay graphvault flowmesh watchgrid forgeops myapify
        wikillm agentshop)

info "Installing ${#SKILLS[@]} skills to ${SKILLS_DIR}/ ..."

for skill in "${SKILLS[@]}"; do
  SRC="${REPO_DIR}/skills/${skill}/SKILL.md"
  DEST_DIR="${SKILLS_DIR}/${skill}"
  DEST="${DEST_DIR}/SKILL.md"

  if [ ! -f "$SRC" ]; then
    warn "Skill source not found: $SRC — skipping"
    continue
  fi

  mkdir -p "$DEST_DIR"
  sed "s/{{NEXUSLAYER_TOKEN}}/${TOKEN}/g" "$SRC" > "$DEST"
  ok "  $skill"
done

# ─── Environment file ─────────────────────────────────────────────────────────

ENV_FILE="${HOME}/.nexuslayer.env"
cat > "$ENV_FILE" <<EOF
# NexusLayer environment — sourced by SDKs and MCP server
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
export NEXUSLAYER_TOKEN="${TOKEN}"
export NEXUSLAYER_API_URL="https://identity.nexuslayer.eu"
export AGENTVAULT_URL="https://vault.nexuslayer.eu"
export WATCHGRID_URL="https://watchgrid.nexuslayer.eu"
export MYAPIFY_API_URL="https://myapify.nexuslayer.eu/api"
export AGENTBRAIN_URL="https://cortex.nexuslayer.eu"
export BRAINVAULT_URL="https://notes.nexuslayer.eu"
export FLOWMESH_URL="https://flowmesh.nexuslayer.eu"
export GRAPHVAULT_URL="https://graph.nexuslayer.eu"
export TASKRELAY_URL="https://tasks.nexuslayer.eu"
export FORGEOPS_URL="https://forgeops.nexuslayer.eu"
export MARKVAULT_URL="https://mark.nexuslayer.eu"
export DOCVAULT_URL="https://docs.nexuslayer.eu"
export MODELROUTER_URL="https://router.nexuslayer.eu"
export SWITCHBOARD_URL="https://switchboard.nexuslayer.eu"
export CODEREVIEWAI_URL="https://review.nexuslayer.eu"
export WIKILLM_URL="https://wikillm.nexuslayer.eu"
export AGENTSHOP_URL="https://agentshop.nexuslayer.eu"
export NEXUSLAYER_SUPPORT_EMAIL="admin@nexuslayer.eu"
EOF
ok "Environment file → ${ENV_FILE}"

# ─── brain CLI helper ─────────────────────────────────────────────────────────

BIN_DIR="${HOME}/.local/bin"
mkdir -p "$BIN_DIR"

cat > "${BIN_DIR}/brain" <<'BRAIN_EOF'
#!/usr/bin/env python3
"""brain — AgentBrain CLI helper for NexusLayer"""
import os, sys, json, urllib.request, urllib.parse, subprocess

BASE  = os.environ.get("AGENTBRAIN_URL", "https://cortex.nexuslayer.eu")
TOKEN = os.environ.get("NEXUSLAYER_TOKEN", "")

# Source env file if token not in environment
if not TOKEN:
    env_file = os.path.expanduser("~/.nexuslayer.env")
    if os.path.exists(env_file):
        for line in open(env_file):
            line = line.strip()
            if line.startswith("export NEXUSLAYER_TOKEN="):
                TOKEN = line.split("=", 1)[1].strip('"\'')
            elif line.startswith("export AGENTBRAIN_URL="):
                BASE = line.split("=", 1)[1].strip('"\'')

def req(method, path, data=None):
    url = BASE.rstrip("/") + path
    body = json.dumps(data).encode() if data else None
    headers = {"Content-Type": "application/json", "Authorization": f"Bearer {TOKEN}"}
    r = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(r, timeout=10) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        print(f"Error {e.code}: {e.read().decode()}", file=sys.stderr)
        sys.exit(1)

cmd = sys.argv[1] if len(sys.argv) > 1 else "help"
args = sys.argv[2:]

if cmd == "context":
    kw = args[0] if args else ""
    r = req("GET", f"/api/context?q={urllib.parse.quote(kw)}")
    for ep in r.get("episodes", r.get("episodic", [])):
        print(f"[episode] {ep.get('content','')[:120]}")
    for l in r.get("lessons", []):
        text = l.get("claim") or l.get("rationale") or l.get("content", "")
        print(f"[lesson]  {text[:120]}")

elif cmd == "push":
    content = args[0] if args else sys.stdin.read()
    # tags is a comma-separated string: the API binds the body as Map<String,String>
    # and rejects a JSON array outright.
    tags    = args[1] if len(args) > 1 else ""
    r = req("POST", "/api/memory/episodic", {"content": content, "tags": tags})
    print(f"Saved episode {r.get('id','?')}")

elif cmd == "working":
    content = args[0] if args else sys.stdin.read()
    tags    = args[1] if len(args) > 1 else ""
    r = req("POST", "/api/memory/working", {"content": content, "tags": tags})
    print(f"Saved working memory {r.get('id','?')}")

elif cmd == "memories":
    r = req("GET", "/api/memory/episodic?page=0&size=10")
    for ep in r.get("content", r if isinstance(r, list) else []):
        print(f"  {str(ep.get('id','')):>6}  {ep.get('content','')[:100]}")

elif cmd == "lessons":
    r = req("GET", "/api/lessons?status=ACCEPTED")
    for l in (r if isinstance(r, list) else r.get("content", r.get("lessons", []))):
        text = l.get("claim") or l.get("rationale") or l.get("content", "")
        print(f"  [{l.get('status','?')}] {text[:100]}")

else:
    print("brain — AgentBrain CLI")
    print("Usage: brain <command> [args]")
    print("  context <keywords>     Load memory context")
    print("  push <text> [tags]     Save an episode")
    print("  working <text> [tags]  Save 24h working memory")
    print("  memories               List recent episodes")
    print("  lessons                List all lessons")
BRAIN_EOF
chmod +x "${BIN_DIR}/brain"
ok "brain CLI → ${BIN_DIR}/brain"

# Check if ~/.local/bin is in PATH
if [[ ":$PATH:" != *":${BIN_DIR}:"* ]]; then
  warn "${BIN_DIR} is not in your PATH."
  echo "   Add this to your ~/.zshrc or ~/.bashrc:"
  echo "   export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# ─── SDKs ─────────────────────────────────────────────────────────────────────

SDK_DEST="${HOME}/.nexuslayer/sdks"
mkdir -p "${SDK_DEST}/python" "${SDK_DEST}/node"

cp "${REPO_DIR}/sdks/python/"*.py "${SDK_DEST}/python/" 2>/dev/null && \
  ok "Python SDKs → ${SDK_DEST}/python/" || warn "No Python SDKs found"

cp "${REPO_DIR}/sdks/node/"*.js "${SDK_DEST}/node/" 2>/dev/null && \
  ok "Node.js SDKs → ${SDK_DEST}/node/" || warn "No Node.js SDKs found"

# ─── Summary ─────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}Installation complete!${NC}"
echo ""
echo "  Skills:  ${SKILLS_DIR}/"
echo "  SDKs:    ${SDK_DEST}/"
echo "  Env:     ${ENV_FILE}"
echo "  CLI:     ${BIN_DIR}/brain"
echo ""
echo "  Dashboard: https://identity.nexuslayer.eu"
echo ""
echo "  To activate the env in your shell:"
echo "  source ~/.nexuslayer.env"
echo ""
echo "  To use SDKs in Python:"
echo "  import sys; sys.path.insert(0, os.path.expanduser('~/.nexuslayer/sdks/python'))"
echo "  from agentvault_sdk import AgentVaultClient"
echo ""
echo "  Restart Claude Code to load the new skills."
echo ""
echo "  Something not working? Email admin@nexuslayer.eu — include the product name"
echo "  and the exact error, and you will get a reply from a human."
echo ""
